In [3]:
#KNN
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.35,random_state=1)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=4)
knn.fit(xtrain,ytrain)
print(knn.score(xtest,ytest))

0.9811320754716981


In [14]:
#Naive Bayes
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.35,random_state=1)

from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(xtrain,ytrain)
print(gnb.score(xtest,ytest))

from sklearn import metrics
ypred=gnb.predict(xtest)
print(metrics.accuracy_score(ytest,ypred))

from sklearn.metrics import confusion_matrix
print(metrics.confusion_matrix(ytest,ypred))

0.9433962264150944
0.9433962264150944
[[19  0  0]
 [ 0 17  2]
 [ 0  1 14]]


In [15]:
#Decision Tree
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.35,random_state=1)

from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(xtrain,ytrain)
print(dt.score(xtest,ytest))

0.9622641509433962


In [18]:
#SVM
from sklearn.datasets import load_iris
x,y=load_iris(return_X_y=True)

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.35,random_state=1)

from sklearn.svm import SVC
svc=SVC(kernel='linear',random_state=0)
svc.fit(xtrain,ytrain)
print(svc.score(xtest,ytest))

ypred=svc.predict(xtest)
ypred_name=[iris.target_names[i] for i in ypred]
print(ypred_name)

1.0
['setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica', 'setosa', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'virginica', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa', 'versicolor', 'setosa', 'setosa', 'virginica']


In [36]:
from numpy import newaxis
#Regression
from sklearn.datasets import load_diabetes
x,y=load_diabetes(return_X_y=True)
x=x[:,newaxis,2]
x.shape

xtrain=x[:-20]
xtest=x[-20:]
ytrain=y[:-20]
ytest=y[-20:]

from sklearn.linear_model import LinearRegression
regr=LinearRegression()
regr.fit(xtrain,ytrain)
ypred=regr.predict(xtest)

from sklearn.metrics import mean_squared_error,r2_score
print(regr.coef_)
print("Mean squared error : %.2f" % mean_squared_error(ytest,ypred))
print("Coefficient of determination : %.2f" %r2_score(ytest,ypred))

[938.23786125]
Mean squared error : 2548.07
Coefficient of determination : 0.47


In [39]:
#K-Means
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data[:,:2]
y=iris.target

from sklearn.cluster import KMeans
km=KMeans()
km=KMeans(n_clusters=3,init='k-means++',n_init=10,max_iter=300,tol=0.0001,verbose=0,random_state=21,copy_x=True,algorithm="auto")
km.fit(x)
centers=km.cluster_centers_
labels=km.labels_
print("New centers",centers)
print("New labels",labels)

New centers [[5.77358491 2.69245283]
 [5.006      3.428     ]
 [6.81276596 3.07446809]]
New labels [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 0 2 0 2 0 2 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0
 2 2 2 2 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 0 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
